### ISSUE TITLE
Change every cursor 

### ISSUE THREAD

**Issue by flashspys** [PandaTeemo/YoloMouse#1]
In games (e.g. LoL) or programs (e.g. Chrome) the default cursor is correctly set by YoloMouse. But if you hover over e.g. a textfield in Chrome or an enemy in LoL the cursor changes to the game default. Is it possible to override even this cursor ?

**Comment by PandaTeemo** [comment]
yes you need to hotkey for each different game cursor.

note some games may use ctrl shift or alt to make that cursor
disappear/change... youll have to either changes those binds or change in
yolo (currently only in settings.ini, ill make it friendlier later :)

**Comment by flashspys** [comment]
Thank you very much !!
