### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by criswell** [PandaTeemo/YoloMouse#4]
It's unclear what license your code is distributed under. It seems to lack any license what-so-ever, which is bad, as it declares an implicit copyright without explaining how others can use your code.

For more information on this problem, and some simple explanations as to what you can do to fix this, please see the following:

https://blog.codinghorror.com/pick-a-license-any-license/

Basically, as it stands now, this is what applies to your code:

> Without a license, the code is copyrighted by default. People can read the code, but they have no legal right to use it. To use the code, you must contact the author directly and ask permission.

So, yeah, anyone using your code is likely doing so at peril.

Please include a license for clarification.

**Comment by sunmachine** [comment]
I know he didn't reply, but I did see the unlicense posted:

https://github.com/PandaTeemo/YoloMouse/blob/master/LICENSE.md

**Comment by criswell** [comment]
Awesome sauce! I'll close this issue then (if I can).
