### ISSUE TITLE
Not all games works.

### ISSUE THREAD

**Issue by leocd91** [PandaTeemo/YoloMouse#5]
Tried to use it on Ragnarok Online but it doesn't work. Also i can't open your old version page.

**Comment by PandaTeemo** [comment]
Ragnarok uses an ancient software cursor method which isnt supported.
Modern games use hardware cursor. You can tell if a game uses software
cursor if it lags and shows up in screenshots.

**Comment by PandaTeemo** [comment]
Btw it still sorta works if you assign YM hotkey, then move cursor off
Ragnarok window then back (in windowed not fullscreen mode). But it will
only overlay and not replace the cursor.
